<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Generate_gwt-Image</name>
   <tag></tag>
   <elementGuidId>93fb3efc-9185-4988-a63d-10bd50152539</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = 'https://zxing.org/w/chart?cht=qr&amp;chs=350x350&amp;chld=L&amp;choe=UTF-8&amp;chl=MECARD%3AN%3Anicho%3BORG%3Apt+abc%3BTEL%3A08781839201%3BURL%3Anicho.com%3BEMAIL%3Anicho%40mail.com%3BADR%3Atangerang+tangerang%3BNOTE%3Aemployee%3B%3B']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.gwt-Image</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='innerresult']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1ad63205-ad41-4369-bef9-1844a7be5ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://zxing.org/w/chart?cht=qr&amp;chs=350x350&amp;chld=L&amp;choe=UTF-8&amp;chl=MECARD%3AN%3Anicho%3BORG%3Apt+abc%3BTEL%3A08781839201%3BURL%3Anicho.com%3BEMAIL%3Anicho%40mail.com%3BADR%3Atangerang+tangerang%3BNOTE%3Aemployee%3B%3B</value>
      <webElementGuid>7012d2dc-3f72-4315-bcec-0f7c85407bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-Image</value>
      <webElementGuid>03541539-0aed-40d9-8099-9184a370524f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;innerresult&quot;)/img[@class=&quot;gwt-Image&quot;]</value>
      <webElementGuid>efdbd558-b48f-40fe-bc5f-ca77b08e8132</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='innerresult']/img</value>
      <webElementGuid>17b144fc-6bcd-4a81-b143-845c6e0aa597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://zxing.org/w/chart?cht=qr&amp;chs=350x350&amp;chld=L&amp;choe=UTF-8&amp;chl=MECARD%3AN%3Anicho%3BORG%3Apt+abc%3BTEL%3A08781839201%3BURL%3Anicho.com%3BEMAIL%3Anicho%40mail.com%3BADR%3Atangerang+tangerang%3BNOTE%3Aemployee%3B%3B')]</value>
      <webElementGuid>5bdee2f7-86ea-4888-8ae4-1bbcb618c93b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>031e7779-d134-4c31-94da-3b40bfabb36a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://zxing.org/w/chart?cht=qr&amp;chs=350x350&amp;chld=L&amp;choe=UTF-8&amp;chl=MECARD%3AN%3Anicho%3BORG%3Apt+abc%3BTEL%3A08781839201%3BURL%3Anicho.com%3BEMAIL%3Anicho%40mail.com%3BADR%3Atangerang+tangerang%3BNOTE%3Aemployee%3B%3B']</value>
      <webElementGuid>41fcea81-1c26-48e8-8713-423aa8a36d01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
