<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Name must be at least 1 character (1)</name>
   <tag></tag>
   <elementGuidId>f0438c62-4757-4d0d-b958-1fe83e3bf21e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='errorMessageID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#errorMessageID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5aad8036-69f8-44a0-8b52-a59af1f10d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>errorMessageID</value>
      <webElementGuid>0dcdbc87-9b3c-4449-a5f5-dc295d8ef5f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>errorMessage</value>
      <webElementGuid>4fd5e546-9cf9-46d3-b7ce-2c103846e8c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Name must be at least 1 character.</value>
      <webElementGuid>5c4f7ede-1f38-4c48-9c47-a2f8977bc9be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;errorMessageID&quot;)</value>
      <webElementGuid>0c5bac70-e4c0-43ba-bd78-b88a411964a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='errorMessageID']</value>
      <webElementGuid>0aaae5ae-aafe-4a58-8b8d-8eccf6c959f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='leftpanel']/tbody/tr[3]/td/span</value>
      <webElementGuid>af78439d-687d-452d-b136-70e5119e9bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Encoding'])[1]/following::span[1]</value>
      <webElementGuid>a66f4532-6e52-49d9-aaca-47a028fa2a56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Memo'])[1]/following::span[1]</value>
      <webElementGuid>03f84aeb-f1b1-4189-b757-c9fa608f6227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Barcode size'])[1]/preceding::span[1]</value>
      <webElementGuid>a6c540cf-b561-43ec-bc17-75ac5ce70ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error correction'])[1]/preceding::span[1]</value>
      <webElementGuid>474abb53-ebe6-4fdc-89c2-c642e69094b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Name must be at least 1 character.']/parent::*</value>
      <webElementGuid>e1cec1a4-2a3c-4dac-b62a-6ced273f7dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span</value>
      <webElementGuid>675b3020-ab9b-4d91-a9cc-6df894c86bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'errorMessageID' and (text() = 'Name must be at least 1 character.' or . = 'Name must be at least 1 character.')]</value>
      <webElementGuid>0774b0c5-5651-4848-bc52-09366e7376a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
