<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Name must be at least 1 character</name>
   <tag></tag>
   <elementGuidId>790c1c10-d8fe-4948-8e38-580d56789877</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='errorMessageID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#errorMessageID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5e95f116-43ca-466d-a55a-44da727f854e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>errorMessageID</value>
      <webElementGuid>3bed8f9e-c870-4959-a66b-6a5d5d9cd248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>errorMessage</value>
      <webElementGuid>c33baa1a-b06a-4734-83ab-728070140610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Name must be at least 1 character.</value>
      <webElementGuid>3f1b438c-e85a-4de5-b46f-d28e0c0bdf22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;errorMessageID&quot;)</value>
      <webElementGuid>25d075b1-b679-4757-8bbd-21f7a8e1bd6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='errorMessageID']</value>
      <webElementGuid>7c471845-918a-4953-90cd-04b67e1e1f7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='leftpanel']/tbody/tr[3]/td/span</value>
      <webElementGuid>3af7e216-895a-4c34-bd94-efe704da558f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Encoding'])[1]/following::span[1]</value>
      <webElementGuid>c015616a-b238-4635-90b2-9ebf1b0afbb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Memo'])[1]/following::span[1]</value>
      <webElementGuid>f73c25b4-e39e-41a1-8699-f76d08354833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Barcode size'])[1]/preceding::span[1]</value>
      <webElementGuid>a78cd4a1-8097-43a3-ba59-ca892f197709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error correction'])[1]/preceding::span[1]</value>
      <webElementGuid>308943e5-a3ae-41c1-9d43-1a84197218a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Name must be at least 1 character.']/parent::*</value>
      <webElementGuid>e9f95124-cf85-4fa9-9659-232b149c7ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span</value>
      <webElementGuid>22894e24-8aec-440d-beb2-3bfca61ae017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'errorMessageID' and (text() = 'Name must be at least 1 character.' or . = 'Name must be at least 1 character.')]</value>
      <webElementGuid>64221d70-527a-4179-be9e-b8979935bb75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
