<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table_ContentsCalendar eventContact informa_cbc713</name>
   <tag></tag>
   <elementGuidId>6cbc351b-dab5-4742-963e-1d8151a4333a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='leftpanel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#leftpanel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>table</value>
      <webElementGuid>23081611-4921-424c-8e84-620d403030af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leftpanel</value>
      <webElementGuid>ecc0e44c-1ea4-4672-a30a-6de2bb31f00e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ContentsCalendar eventContact informationEmail addressGeo locationPhone numberSMSTextURLWifi networkNameCompanyTitlePhone numberEmailAddressAddress 2WebsiteMemoEncodingMECARDvCard Barcode sizeSmallMediumLargeError correctionLMQHCharacter encodingUTF-8ISO-8859-1Shift_JIS Generate →</value>
      <webElementGuid>2f601356-dead-4624-a6f2-f587f778cbcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftpanel&quot;)</value>
      <webElementGuid>f463cbf4-5002-4a1b-bbd2-45ca3389face</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//table[@id='leftpanel']</value>
      <webElementGuid>f7164bc7-cbe5-4492-bee7-3a3370891643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='mainpanel']/tbody/tr/td/table</value>
      <webElementGuid>52d1a2b4-e896-4f51-9501-7e6424e8ce7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='from the ZXing Project'])[1]/following::table[2]</value>
      <webElementGuid>fc0a4f60-49e3-4914-b35e-02c8d65e2225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table</value>
      <webElementGuid>47822ac3-981a-465d-ba16-012bdc2ce36d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//table[@id = 'leftpanel' and (text() = 'ContentsCalendar eventContact informationEmail addressGeo locationPhone numberSMSTextURLWifi networkNameCompanyTitlePhone numberEmailAddressAddress 2WebsiteMemoEncodingMECARDvCard Barcode sizeSmallMediumLargeError correctionLMQHCharacter encodingUTF-8ISO-8859-1Shift_JIS Generate →' or . = 'ContentsCalendar eventContact informationEmail addressGeo locationPhone numberSMSTextURLWifi networkNameCompanyTitlePhone numberEmailAddressAddress 2WebsiteMemoEncodingMECARDvCard Barcode sizeSmallMediumLargeError correctionLMQHCharacter encodingUTF-8ISO-8859-1Shift_JIS Generate →')]</value>
      <webElementGuid>c981dc91-d1d0-4de4-ad62-3cd4802b0db7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
