<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_QR code image_qrcode</name>
   <tag></tag>
   <elementGuidId>0c88516e-8f44-4d2a-8ce8-3e0abccdaeb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='qrcode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#qrcode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bcd6718f-9987-4c1f-8c8f-ef85a4e8826c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>3513c954-8c8d-44d9-8b58-f44ddab1bd5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>qrcode</value>
      <webElementGuid>3f9c82c1-dbb4-4428-abbb-32ab0b61234c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qrcode</value>
      <webElementGuid>2ec96f9b-9b95-44cb-a005-7f0aee89d0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.png</value>
      <webElementGuid>fc2ddf3f-dd07-4624-977c-d5c6713f05d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qrcode&quot;)</value>
      <webElementGuid>189dac21-5289-4428-afea-fa14675b03cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='qrcode']</value>
      <webElementGuid>854ffdae-7794-4cb7-b0de-968b497e94d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='qrform']/div/input</value>
      <webElementGuid>ea310168-1543-4a49-a0df-9c75f83b267d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9d46cce0-f2bf-4fc7-86ee-eb0e692639e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'qrcode' and @id = 'qrcode']</value>
      <webElementGuid>ac909b8c-10d1-44cc-b9b9-9db4507442f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
