<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Decoded_decoded</name>
   <tag></tag>
   <elementGuidId>760b1792-8a06-4293-aaad-f9f1640205b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#decoded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='decoded']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>dc5bf8d2-67bf-45af-b99f-d00da9e5e31d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>decoded</value>
      <webElementGuid>bbf5c27e-f663-408f-aae2-778012c5f608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>b4c884b1-1106-4b03-b1f5-176acf3475c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>af67f1fc-fb21-4477-a8ea-e19f6f4cb659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;decoded&quot;)</value>
      <webElementGuid>81a04d1a-65a1-470a-b812-9b8cf738741f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='decoded']</value>
      <webElementGuid>b6e3ba9e-c6ee-49c5-909c-cbdde7e0d8f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>e5d487b8-bab1-4bd6-ad0b-efd57b164dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'decoded']</value>
      <webElementGuid>57dbcfae-5402-459d-8c6d-0643e19b02ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
